modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="https://github.com/byalexeykh/AdvancedCombatSystem/issues" #optional
logoFile="logo.png" #optional
[[mods]] #mandatory
modId="advancedcombatsystem" #mandatory
version="0.2.1" #mandatory
displayName="Advanced Combat System" #mandatory
updateJSONURL="https://raw.githubusercontent.com/byalexeykh/AdvancedCombatSystem/master/src/main/resources/update.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/advanced-combat-system" #optional
credits="-" #optional
authors="byalexeykh aka Epic_Slime" #optional
description='''
Deepening and complicating the combat system by adding new and replacing old mechanics.
'''
