modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="advancedcombatsystem" #mandatory
version="0.1.0" #mandatory
displayName="Advanced Combat System" #mandatory
# updateJSONURL="" #optional
# displayURL="http://parasha.net/" #optional
logoFile="examplemod.png" #optional
credits="byalexeykh aka Epic_Slime" #optional
authors="byalexeykh aka Epic_Slime" #optional
description='''
Deepening and complicating the combat system by adding new and replacing old mechanics.
'''
